### ISSUE TITLE
Deploy witnet-pricefeed-example contracts to Rinkeby

### ISSUE THREAD

**Issue by mariocao** [witnet/research#104]

**Comment by girazoki** [comment]
Merged the 3 price-feeds in https://github.com/stampery-labs/witnet-price-feeds-examples/pull/1. Deployed all of them in rinkeby with addresses:

BtcUsdPriceFeed: 0x82CDC5a0Befe3198ca9Df4a9F542061522eD385B
 EthUsdPriceFeed: 0xc2Fb2a4A735A77e557483EC210909C20809f4F1a
 GoldEurPriceFeed: 0x68A5F47B0913b06347fd79D1311Eec1f30c0004d
WitnetPriceFeedsAggregator: 0xde66d0611CadFC79Aad55DADBE01C8633eE7C214
