### ISSUE TITLE
Define the Witnet reputation system proposal

### ISSUE THREAD

**Issue by mariocao** [witnet/research#22]
In order to define a reputation system proposal, the following tasks should be followed:

- [x] Research caducity strategy
- [x] Research decay (log-exp) strategy
- [x] Implement simulation scripts
- [x] Strategies comparison
- [x] Parameters fine-tuning
- [ ] Write report

**Comment by mariocao** [comment]
**Highlights of research outcome**

- Both approaches seem to offer a degree of unpredictability, and both offer advantages to those nodes proving to behave honestly.
- The **caducity approach offers higher unpredictability**, and in consequence, a higher defense against sybil attacks.
- The **log-exp approach seems to be more effective** in terms of how often honest nodes are selected for committees (therefore, being more predictive).
- The caducity approach penalizes with some reputation falls to those nodes that behaved honestly (and therefore, is less effective)
- The **log-exp approach has a smaller footprint** as it only needs to know the reputation state per epoch.
- The caducity approach is a bit more costly memory-wise, as a memory footprint on the reputation activity over the last epochs has to be maintained (to know when each gained reputation expires)

**Comment by mariocao** [comment]
**Log-exp demurrage**

![Figure_1](https://user-images.githubusercontent.com/12464544/55241131-bdf45d00-523a-11e9-9a5a-6299fca41a30.png)

![Figure_1b](https://user-images.githubusercontent.com/12464544/55241142-c351a780-523a-11e9-96dc-48a5f86d69e7.png)

**Comment by girazoki** [comment]
![cad_1](https://user-images.githubusercontent.com/18615930/55241298-13306e80-523b-11e9-9cc1-2fef9074ab97.png)
![cad_2](https://user-images.githubusercontent.com/18615930/55241302-14fa3200-523b-11e9-8fa7-92916c1ea5da.png)

**Comment by mariocao** [comment]
[Report link](https://docs.google.com/document/d/1dcAZCieKfWiBErTAN6O6p2cOOekmWOkKMqG2bLl_dPc/edit?usp=sharing)

The definition of the _Active Reputation Set_ was not included in this research (issue #23).
