### ISSUE TITLE
Create a schedule for further research publications

### ISSUE THREAD

**Issue by aesedepece** [witnet/research#28]

**Comment by mariocao** [comment]
**Incoming posts**

- Reputation System Challenges - Under review
- Reputation Initialization - Under review
- Preventing Sybil Attacks without PoW (and PoS) - 80% ready

**Next topics for potentials posts**

- Demurrage report
- Research on bridges

Doc: [Roadmap](https://docs.google.com/document/d/1gdEWxdt0ylpfciJhyIotgaxbRPBS4vPyeJV2FntInRQ/edit?usp=sharing)
