### ISSUE TITLE
Assess BLS libraries

### ISSUE THREAD

**Issue by mariocao** [witnet/research#81]
The goal is to assess the libraries for using BLS signatures in the `witnet-rust` nodes. They should be compatible with our solidity smart contracts.

**Comment by girazoki** [comment]
There are a couple considerations to take into account.
- The subsidized curve in Ethereum is the Alt_bn128 curve (a.k.a bn256). Thus, the library should be capable of handling such curve. In the future Ethereum might subsidize other curves (even the BLS12-381 that Eth2.0 is intending to use), but for the moment we stay with the alt_bn128.
- If possible, a library for which the sign and verify methods are implemented could be used

We found the following BLS libraries with the Signing and Verification functions implemented:
- bls (https://github.com/str4d/bls). Uses BLS12-381.
- bls-signatures (https://github.com/filecoin-project/bls-signatures). Uses the paired crate, which only supports BLS12-381.
- bls_acml (https://github.com/lovesh/signature-schemes/tree/master/bls). Uses the amcl_wrapper crate which only supports BLS12-381.
- bls_like (https://github.com/w3f/bls).  Again uses the paired crate.
- bls_sigs_ref (https://github.com/algorand/bls_sigs_ref). Uses the pairing-plus crate (https://github.com/algorand/pairing-plus) but again only supports BLS12-381

After these results we decided to look for a library that implements the necessary curve logic and build the library ourselves, with special attention to the structure in https://github.com/celo-org/bls-zexe. Obviously, the aforementioned crates are discarded for only supporting the BLS12-381 curve:

- paired
- pairing-plus
- acml_wrapper
