### ISSUE TITLE
Mainnet protocol constants

### ISSUE THREAD

**Issue by mariocao** [witnet/research#94]
Discussion about mainnet protocol constants

**Comment by lrubiorod** [comment]
Conclusions:
- Increase the block weight to 150K, the activity period to 2000 epochs and the alpha clock to 20000 witnesses acts. (https://github.com/witnet/witnet-rust/pull/1092)
- Apply and validate separated max block weight for value transfer and data requests. (https://github.com/witnet/witnet-rust/issues/1093)
- Assesment: Relative limit of witnesses in a data request. (https://github.com/witnet/witnet-rust/issues/1094)
- Assesment: Progressive redistribution of the penalised and expirated reputation  (https://github.com/witnet/witnet-rust/issues/1095)
- Assesment: creation of blocklist and allowlist of data request sources to prevent inconsistence source attacks (https://github.com/witnet/witnet-rust/issues/1096)
- Experimental testing: create different setups with different proposals to test and obtain experimental measures about the system behaviour (https://github.com/witnet/witnet-rust/issues/1097)
- Assesment: specify a limit of data requests or sources to resolve (https://github.com/witnet/witnet-rust/issues/1098)
