### ISSUE TITLE
Specify collaterals

### ISSUE THREAD

**Issue by mariocao** [witnet/research#97]
We want to work on publishing a WIP that:
> introduces an upgrade that strengthens the overall security of the Witnet protocol by means of hindering any chance for an attacker to operate an unbounded number of identities with views to tamper with data requests or abusing any of the protocol shared data structures (e.g. ARS and TRS).

This crucial security feature is achieved by:
>  requiring witnesses to commit a certain amount of tokens to each of their commitment transactions, alike to a collateral, deposit or bond that they can only recoup if they abide by the protocol and pass the filters of the eventual tally function, in a similar fashion to the current reputation protocol.

**Comment by aesedepece** [comment]
The specification is being worked here:
https://hackmd.io/wwu_mZ-aRziGDzWTKN1AzA

**Comment by aesedepece** [comment]
Took me 9 days but the specification is ready:
https://hackmd.io/wwu_mZ-aRziGDzWTKN1AzA?view

Unless there's some strong objection, I will submit it as a [WIP] in the next 24h.

[WIP]: https://github.com/witnet/wips
